@file:Suppress("SpellCheckingInspection")

package page.ooooo.geoshare.lib.android

const val AMAP_PACKAGE_NAME = "com.autonavi.minimap"
const val BAIDU_MAP_PACKAGE_NAME = "com.baidu.BaiduMap"
const val COMAPS_FDROID_PACKAGE_NAME = "app.comaps.fdroid"
const val COMAPS_PACKAGE_NAME_PREFIX = "app.comaps."
const val GARMIN_PACKAGE_NAME_PREFIX = "com.garmin."
const val GARMIN_EXPLORE_PACKAGE_NAME = "${GARMIN_PACKAGE_NAME_PREFIX}android.apps.explore"
const val GMAPS_WV_PACKAGE_NAME = "us.spotco.maps"
const val GOOGLE_MAPS_PACKAGE_NAME = "com.google.android.apps.maps"
const val HERE_WEGO_PACKAGE_NAME = "com.here.app.maps"
const val KOMOOT_PACKAGE_NAME = "de.komoot.android"
const val LOCUS_MAP_PACKAGE_NAME = "menion.android.locus"
const val MAGIC_EARTH_PACKAGE_NAME = "com.generalmagic.magicearth"
const val MAPS_ME_PACKAGE_NAME = "com.mapswithme.maps.pro"
const val MAPY_COM_PACKAGE_NAME = "cz.seznam.mapy"
const val OEFFI_PACKAGE_NAME = "de.schildbach.oeffi"
const val ORGANIC_MAPS_PACKAGE_NAME = "app.organicmaps"
const val OSMAND_PACKAGE_NAME = "net.osmand"
const val OSMAND_PLUS_PACKAGE_NAME = "net.osmand.plus"
const val SYGIC_PACKAGE_NAME = "com.sygic.aura"
const val TEST_PACKAGE_NAME = "com.example.test"
const val TOMTOM_PACKAGE_NAME_PREFIX = "com.tomtom."
const val TOMTOM_PACKAGE_NAME = "${TOMTOM_PACKAGE_NAME_PREFIX}speedcams.android.map"
const val VESPUCCI_PACKAGE_NAME = "de.blau.android"
